/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movielist01;

import Singleton.MovieData;
import Singleton.UserData;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RentAMovie extends javax.swing.JFrame {

    
    // initialize singleton class
    UserData singletonUser = new UserData();
    MovieData singletonMovie = new MovieData();
    
    private int selected_movie_list_row = 0;
    private int  selected_movie_id = 0;
    private String selected_movie_title = "";
    private int selected_movie_price = 0;
    /**
     * Creates new form RentAMovie
     */
    public RentAMovie() {
        initComponents();
        availableMovieTable();
        setUser();
    }

    private void setUser() {
        complete_name_label.setText(singletonUser.SELECTED_USER_FIRSTNAME + " " + singletonUser.SELECTED_USER_LASTNAME);
        address_label.setText(singletonUser.SELECTED_USER_ADDRESS);
    }
    
    DefaultTableModel available_movie_model = new DefaultTableModel();
    private void availableMovieTable() {
        String[] columnNames = {"NUMBER", "TITLE", "PRICE"};
        int movie_id = 0;
        String movie_title = "";
        int movie_price = 0;
        available_movie_model.setColumnIdentifiers(columnNames);
        available_movies_table.setModel(available_movie_model);
        ResultSet movie_list = singletonMovie.AVAILABLE_MOVIE;
        try {
            while ( movie_list.next() ) {
                movie_title = movie_list.getString("title");
                movie_price = movie_list.getInt("price");
                movie_id = movie_list.getInt("id");
                available_movie_model.addRow(new Object[]{movie_id, movie_title, movie_price});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        available_movies_table = new javax.swing.JTable();
        rent_movie_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        user_cart_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rent_total_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        complete_name_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Available Movie List");

        available_movies_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMBER", "TITLE", "PRICE"
            }
        ));
        available_movies_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                available_movies_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(available_movies_table);

        rent_movie_button.setText("Rent");
        rent_movie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rent_movie_buttonActionPerformed(evt);
            }
        });

        user_cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMBER", "TITLE", "PRICE"
            }
        ));
        jScrollPane2.setViewportView(user_cart_table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CART");

        jButton2.setText("Proced to Checkout");

        jLabel3.setText("Total : ");

        rent_total_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rent_total_fieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NAME :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ADDRESS :");

        complete_name_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        complete_name_label.setText("jLabel6");

        address_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address_label.setText("jLabel7");

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jDesktopPane1.setForeground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rent_movie_button)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rent_total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(complete_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rent_movie_button)
                .addGap(19, 19, 19)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(complete_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rent_total_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rent_total_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rent_total_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rent_total_fieldActionPerformed

    DefaultTableModel cart_model = new DefaultTableModel();
    int movie_total = 0;
    private void rent_movie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rent_movie_buttonActionPerformed
        // TODO add your handling code here:
        
       // ((available_movie_model)available_movies_table.getModel()).removeRow(selected_movie_row);
        available_movie_model.removeRow(selected_movie_list_row);
        
        String[] columnNames = {"NUMBER", "TITLE", "PRICE"};
        movie_total = movie_total + selected_movie_price;
        
        cart_model.setColumnIdentifiers(columnNames);
        user_cart_table.setModel(cart_model);
        try {
                cart_model.addRow(new Object[]{selected_movie_id, selected_movie_title, selected_movie_price});
           
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        rent_total_field.setText(String.valueOf((int)movie_total));

    }//GEN-LAST:event_rent_movie_buttonActionPerformed

    private void available_movies_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_available_movies_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)available_movies_table.getModel();
        selected_movie_list_row = available_movies_table.getSelectedRow();
        selected_movie_id = (int)model.getValueAt(selected_movie_list_row, 0);
        selected_movie_title = (String)model.getValueAt(selected_movie_list_row, 1);
        selected_movie_price = (int)model.getValueAt(selected_movie_list_row, 2);
        
        //System.out.println("movie_id : " + movie_id + ", movie_title : " + movie_title + ", movie_price : " +movie_price);
    }//GEN-LAST:event_available_movies_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTable available_movies_table;
    private javax.swing.JLabel complete_name_label;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rent_movie_button;
    private javax.swing.JTextField rent_total_field;
    private javax.swing.JTable user_cart_table;
    // End of variables declaration//GEN-END:variables
}
